# Generated by Django 6.0.5 on 2026-05-14 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='galaxies/')),
                ('distance_from_earth_ly', models.FloatField(blank=True, help_text='Distance from Earth in light years', null=True)),
            ],
            options={
                'verbose_name_plural': 'Galaxies',
            },
        ),
        migrations.CreateModel(
            name='CelestialBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body_type', models.CharField(choices=[('star', 'Star'), ('planet', 'Planet'), ('moon', 'Moon'), ('asteroid', 'Asteroid'), ('comet', 'Comet'), ('blackhole', 'Black Hole'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='celestial_bodies/')),
                ('mass_kg', models.FloatField(blank=True, help_text='Mass in kilograms', null=True)),
                ('radius_km', models.FloatField(blank=True, help_text='Radius in kilometers', null=True)),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celestial_bodies', to='universe.galaxy')),
            ],
            options={
                'verbose_name_plural': 'Celestial Bodies',
            },
        ),
    ]
