# Generated by Django 6.0.5 on 2026-05-14 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Object Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AstronomicalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.TextField(help_text='A brief summary')),
                ('full_description', models.TextField()),
                ('diameter_km', models.FloatField(blank=True, help_text='Diameter in kilometers', null=True)),
                ('mass', models.CharField(blank=True, help_text="Mass (e.g., '5.97 x 10^24 kg')", max_length=100, null=True)),
                ('distance_from_earth', models.CharField(blank=True, help_text="Distance from Earth (e.g., '4.24 light-years')", max_length=100, null=True)),
                ('formation', models.CharField(blank=True, help_text='Estimated age or formation period', max_length=200, null=True)),
                ('discovered_by', models.CharField(blank=True, max_length=200, null=True)),
                ('discovery_date', models.CharField(blank=True, help_text='Date or era of discovery', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='astronomical_objects/')),
                ('scientific_fact', models.TextField(blank=True, null=True)),
                ('comparison_to_earth', models.TextField(blank=True, null=True)),
                ('scale_level', models.IntegerField(default=0, help_text='Used for scale comparisons (e.g., 1=Planet, 2=Star)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astronomical_objects', to='universe.objectcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='CelestialBody',
        ),
        migrations.DeleteModel(
            name='Galaxy',
        ),
    ]
